services:
  makeja_image:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    links:
      - db


 
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: makeja_dev
      POSTSGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U makeja_dev"]
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
